apiVersion: v1
kind: ConfigMap
metadata:
  name: script-service-b
  namespace: service-b-ns
data:
  server.js: |
    import * as http from 'node:http';

    const server = http.createServer((req, res) => {
      res.writeHead(200, {'Content-Type': 'application/json'});
      const responseData = {
        message: 'Hello from service-b!',
        path: req.url
      };
      res.end(JSON.stringify(responseData));
    });

    server.listen(8080, '0.0.0.0', () => {
      console.log('Server running on port 8080');
    });
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  namespace: service-b-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      #   runAsGroup: 3000
      #   fsGroup: 2000
      #   seccompProfile:
      #     type: RuntimeDefault
      containers:
      - name: server
        image: node:alpine
        command: ["node", "/scripts/server.js"]
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   readOnlyRootFilesystem: true
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   runAsGroup: 3000
        #   seccompProfile:
        #     type: RuntimeDefault
        #   capabilities:
        #     drop:
        #       - ALL
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: script-service-b
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: service-b-ns
spec:
  selector:
    app: service-b
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP  # Or LoadBalancer/NodePort as needed
