server:
  port: 8443
  ssl:
    bundle: server
    client-auth: NEED

management:
  server:
    port: 8080
    ssl:
      enabled: false

spring:
  application:
    name: quote-service
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: /certs/tls.crt
            private-key: /certs/tls.key
          truststore:
            certificate: /certs/ca.crt
          reload-on-update: true
